[theme]

primaryColor="#56C596"

backgroundColor="#FFFFFF"

secondaryBackgroundColor="#EFFFF7"

textColor="#222222"

font="sans serif"


[server]

headless=true

enableCORS=false

enableXsrfProtection=false
